# Change these first
owner: ilger03 # Your GitHub organization or username, where this repository lives
repo: Uptime # The name of this repository

sites:

  - name: GEOFIN1
    url: $GEOFIN1

  - name: WEB04_ZEUS
    url: $WEB04_ZEUS

  - name: HOSTING_WIN3
    url: $HOSTING_WIN3

  - name: ZIM_LICENSE
    url: $ZIM_LICENSE

  - name: CLOUDOFFICE01
    url: $CLOUDOFFICE01

  - name: VCLOUD_HOTELTURIST
    url: $VCLOUD_HOTELTURIST
    
  - name: SMTP2_ILGER
    check: "tcp-ping"
    url: $SMTP2_ILGER
    port: 25

  - name: SMTP4_ILGER
    check: "tcp-ping"
    url: $SMTP4_ILGER
    port: 25

  - name: SMTP5_ILGER
    check: "tcp-ping"
    url: $SMTP5_ILGER
    port: 25

  - name: SMTP6_ILGER
    check: "tcp-ping"
    url: $SMTP6_ILGER
    port: 25

  - name: SMTPMEDICASA
    check: "tcp-ping"
    url: $SMTPMEDICASA
    port: 25

  - name: WPZADMIN7
    url: $WPZADMIN7

  - name: HOSTING5_ILGER
    url: $HOSTING5_ILGER

  - name: HOSTING6_ILGER
    url: $HOSTING6_ILGER

  - name: HOSTING7_ILGER
    url: $HOSTING7_ILGER

  - name: WEB06_ZEUS
    url: $WEB06_ZEUS

  - name: FOTI1_ILGER
    url: $FOTI1_ILGER

  - name: FOTI2_ILGER
    url: $FOTI2_ILGER

  - name: ECOLINEWASH3
    url: $ECOLINEWASH3

  - name: LACASADELFORMAGGIO
    url: $LACASADELFORMAGGIO

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  name: ilger
  logoUrl: https://www.ilger.com/wp-content/uploads/2021/11/ILGER-logo.png
  baseUrl: /Uptime
  icon: https://www.ilger.com/wp-content/uploads/2022/03/ilger-logo-favicon.png
  introTitle: "Page - 4"
  introMessage: Status page with **real-time** data
  
  navbar:
    - title: Page1
      href: https://ilger00.github.io/Uptime/
    - title: Page2
      href: https://ilger01.github.io/Uptime/
    - title: Page3
      href: https://ilger02.github.io/Uptime/
    - title: Page4
      href: /Uptime
    - title: Page5
      href: https://ilger04.github.io/Uptime/
    - title: Page6
      href: https://ilger05.github.io/Uptime/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
